default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mini_url_development

test:
  <<: *default
  database: mini_url_test

production:
  <<: *default
  database: mini_url_production
