# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a18f288f8e7a52a9361f57b71f1f89e5e79a7bbea23dce131039f91c20b074ee6586ea186a3c0950c33cef010e7b582a9a2e20565b86b945eedcecbad68940d7

test:
  secret_key_base: c0168a6bc9e5142d84b26f147e4045bf5486b1bbb22e03f9e8723fe04686dd2ba6d5a80faea47ebba5dd8a6dfcd34b6aa38f57677fcf9eb3f4bd440f785d4831

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
